// <auto-generated />
using System;
using AutoGlassApi.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoGlassApi.Infra.Data.Migrations
{
    [DbContext(typeof(AutoGlassApiDbContext))]
    [Migration("20230322181950_CriacaoDB")]
    partial class CriacaoDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("AutoGlassApi.Domain.Entities.Produto", b =>
                {
                    b.Property<int?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CnpjFornecedor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CodigoFornecedor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFabricacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoFornecedor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Situacao")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.HasIndex("DataFabricacao");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            CnpjFornecedor = "12.983.451/0001-01",
                            CodigoFornecedor = 1,
                            DataFabricacao = new DateTime(2023, 1, 29, 15, 8, 0, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2028, 1, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Vidro",
                            DescricaoFornecedor = "Fornecedor 1",
                            Situacao = 0
                        },
                        new
                        {
                            Codigo = 2,
                            CnpjFornecedor = "12.983.451/0001-01",
                            CodigoFornecedor = 1,
                            DataFabricacao = new DateTime(2022, 11, 18, 9, 55, 18, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2026, 11, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Retrovisor",
                            DescricaoFornecedor = "Fornecedor 1",
                            Situacao = 0
                        },
                        new
                        {
                            Codigo = 3,
                            CnpjFornecedor = "12.983.451/0001-01",
                            CodigoFornecedor = 1,
                            DataFabricacao = new DateTime(2019, 10, 22, 8, 45, 23, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2030, 10, 22, 8, 45, 23, 0, DateTimeKind.Unspecified),
                            Descricao = "Pelicula",
                            DescricaoFornecedor = "Fornecedor 1",
                            Situacao = 1
                        },
                        new
                        {
                            Codigo = 4,
                            CnpjFornecedor = "45.781.394/0001-02",
                            CodigoFornecedor = 2,
                            DataFabricacao = new DateTime(2022, 12, 13, 12, 42, 56, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2024, 10, 1, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Lanterna",
                            DescricaoFornecedor = "Fornecedor 2",
                            Situacao = 0
                        },
                        new
                        {
                            Codigo = 5,
                            CnpjFornecedor = "45.781.394/0001-02",
                            CodigoFornecedor = 2,
                            DataFabricacao = new DateTime(2023, 2, 22, 9, 15, 32, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2025, 2, 22, 9, 15, 32, 0, DateTimeKind.Unspecified),
                            Descricao = "Lampada",
                            DescricaoFornecedor = "Fornecedor 2",
                            Situacao = 0
                        },
                        new
                        {
                            Codigo = 6,
                            CnpjFornecedor = "45.781.394/0001-02",
                            CodigoFornecedor = 2,
                            DataFabricacao = new DateTime(2021, 8, 7, 14, 24, 35, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2023, 8, 20, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Farol",
                            DescricaoFornecedor = "Fornecedor 2",
                            Situacao = 0
                        },
                        new
                        {
                            Codigo = 7,
                            CnpjFornecedor = "45.781.394/0001-02",
                            CodigoFornecedor = 2,
                            DataFabricacao = new DateTime(2023, 1, 15, 9, 37, 0, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Higienizacao",
                            DescricaoFornecedor = "Fornecedor 2",
                            Situacao = 1
                        },
                        new
                        {
                            Codigo = 8,
                            CnpjFornecedor = "55.425.738/0001-47",
                            CodigoFornecedor = 3,
                            DataFabricacao = new DateTime(2022, 7, 8, 18, 15, 17, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2032, 7, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Para-choque",
                            DescricaoFornecedor = "Fornecedor 3",
                            Situacao = 0
                        },
                        new
                        {
                            Codigo = 9,
                            CnpjFornecedor = "55.425.738/0001-47",
                            CodigoFornecedor = 3,
                            DataFabricacao = new DateTime(2023, 3, 2, 11, 18, 0, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2025, 9, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Lataria",
                            DescricaoFornecedor = "Fornecedor 3",
                            Situacao = 1
                        },
                        new
                        {
                            Codigo = 10,
                            CnpjFornecedor = "55.425.738/0001-47",
                            CodigoFornecedor = 3,
                            DataFabricacao = new DateTime(2022, 12, 31, 15, 32, 15, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2025, 12, 31, 15, 32, 15, 0, DateTimeKind.Unspecified),
                            Descricao = "Suspensao",
                            DescricaoFornecedor = "Fornecedor 3",
                            Situacao = 0
                        },
                        new
                        {
                            Codigo = 11,
                            CnpjFornecedor = "55.425.738/0001-47",
                            CodigoFornecedor = 3,
                            DataFabricacao = new DateTime(2021, 5, 30, 11, 40, 45, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2024, 5, 30, 11, 40, 45, 0, DateTimeKind.Unspecified),
                            Descricao = "Palheta",
                            DescricaoFornecedor = "Fornecedor 3",
                            Situacao = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
